/* Auto-generated by genmsg_cpp for file /home/jia/kinetic_workspace/sandbox/beginner_tutorials/msg/Num.msg */
#ifndef BEGINNER_TUTORIALS_MESSAGE_NUM_H
#define BEGINNER_TUTORIALS_MESSAGE_NUM_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct Num_ {
  typedef Num_<ContainerAllocator> Type;

  Num_()
  : w1(0.0)
  , w2(0.0)
  , w3(0.0)
  {
  }

  Num_(const ContainerAllocator& _alloc)
  : w1(0.0)
  , w2(0.0)
  , w3(0.0)
  {
  }

  typedef float _w1_type;
  float w1;

  typedef float _w2_type;
  float w2;

  typedef float _w3_type;
  float w3;


  typedef boost::shared_ptr< ::beginner_tutorials::Num_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::Num_<ContainerAllocator>  const> ConstPtr;
}; // struct Num
typedef  ::beginner_tutorials::Num_<std::allocator<void> > Num;

typedef boost::shared_ptr< ::beginner_tutorials::Num> NumPtr;
typedef boost::shared_ptr< ::beginner_tutorials::Num const> NumConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::beginner_tutorials::Num_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::beginner_tutorials::Num_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::beginner_tutorials::Num_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::beginner_tutorials::Num_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::Num_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bd82aec785cf5731a7d25a0042e76809";
  }

  static const char* value(const  ::beginner_tutorials::Num_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xbd82aec785cf5731ULL;
  static const uint64_t static_value2 = 0xa7d25a0042e76809ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::Num_<ContainerAllocator> > {
  static const char* value() 
  {
    return "beginner_tutorials/Num";
  }

  static const char* value(const  ::beginner_tutorials::Num_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::Num_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 w1\n\
float32 w2\n\
float32 w3\n\
\n\
";
  }

  static const char* value(const  ::beginner_tutorials::Num_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::beginner_tutorials::Num_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::Num_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.w1);
    stream.next(m.w2);
    stream.next(m.w3);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER
}; // struct Num_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::Num_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::beginner_tutorials::Num_<ContainerAllocator> & v) 
  {
    s << indent << "w1: ";
    Printer<float>::stream(s, indent + "  ", v.w1);
    s << indent << "w2: ";
    Printer<float>::stream(s, indent + "  ", v.w2);
    s << indent << "w3: ";
    Printer<float>::stream(s, indent + "  ", v.w3);
  }
};


} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_NUM_H

